### PR TITLE
I27 blurb

### LINKED ISSUE #27: Blurb Command
This command gives an "at a glance" look at a team's season at the current time.  Expected usage is something like: `!blurb bayern munich`.  The output should be an embedded message that contains the following:
- record
- points
- league position
- last 2 match results
- upcoming match

### PR DESCRIPTION
**Pull request by nikola-rados**
# Description
- add `blurb` command
- restructure some of the files/directories
- generalize several functions
- add `utils` file
- create `embedder`
- other small things I'm forgetting

screenshpt

Resolves #27 

## Special Notes
I ended up only getting the most recent result rather than the most recent 2 results.  I felt it was a bit unnecessary to go further back.

## Suggested Version Bump
- [ ] Major
- [x] Minor
- [ ] Patch

# Checklist:
- [x] I have run `black .`
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added logging

### CODE REVIEW

**Comment by maxUser** [comment]
I'm having an issue with using teams with umlauts in their names as arguments. I tried Koln, Dusseldorf, Köln, Düsseldorf,  Duesseldorf, Koeln. None were recognized by the bot.

**Comment by nikola-rados** [comment]
@maxUser good find, it **is** in fact an issue.  At a glance it looks like its from extracting the team from the league table. Working on it.

**Comment by nikola-rados** [comment]
A fix has been pushed in the form of a de-accenting method.  You can now use either accented or non-accented inputs.  I think our current strategy isn't robust against team names with multiple accented letters.  I'm not sure how comment that is in german but it may be something to consider for the future.

screenshot

**Review by maxUser — APPROVED** [review]
I really like this. I think we can do a lot more with it as well. Code looks really nice too - helped me to improve my own :) the only thing that I scratch my head at is why it takes like 5 seconds after typing the command for the blurb to pop up.

**Pull request merged**
